spring:
  application:
    name: zd-ai-code-backend
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sht.zdaicode.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
