spring:
  application:
    name: zd-ai-code-backend
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hd_ai_code
    username: root
    password: 20040223tian
  # redis
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      username: default
      password: "20040223tian"
      ttl: 3600



  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sht.zdaicode.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
