spring:
  application:
    name: zd-ai-code-backend
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hd_ai_code
    username: root
    password: 20040223tian
  # redis
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      username: default
      password: "20040223tian"
      ttl: 3600
  session:
    store-type: redis
    timeout: 2592000



  profiles:
    active: local

# 阿里云OSS对象存储配置
oss:
  client:
    host: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5t5Zev6gad9dZh9MzeHH
    accessKeySecret: 85FVI0zZQS1GVRaeQ6bcPXlDuexgJa
    region: oss-cn-beijing
    bucket: hd-ai0223

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sht.zdaicode.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

# Pixabay API配置
pixabay:
  api-key: 52245879-ba334dd800c5f8cd30aaee568

# Pexels API配置（如果需要）
pexels:
  api-key: YOUR_PEXELS_API_KEY_HERE
